### ISSUE TITLE
Potential typos in mold.sh.in

### ISSUE THREAD

**Issue by ghost** [ptr1337/makepkg-optimize#1]
Hi, came across the interesting [makepkg-optimize-mold](https://aur.archlinux.org/packages/makepkg-optimize-mold/) in the AUR. Going over the files I was wondering if there are typos in the mold.sh.in file. It references `CFLAGS+="$moldflags"` twice and also references `CLAGS+="$moldflags"`. Is this intended?

https://github.com/ptr1337/makepkg-optimize/blob/7a105e20bd0f8d6353adc03016645697f61377ec/mold.sh.in#L16-L22

**Comment by ptr1337** [comment]
Wow, thanks for the reporting this typo. 
Im a retard. Will be sloved.

**Comment by ptr1337** [comment]
I fixed it now. Also i have changed the naming of the lto flags, since arch alreads uses lto (!lto) as default option. 
So i just changed that to lto-gcc and thats it. 

Also ive added a patch, which includes for GCC versions under 12 a normal support for mold. Also in the latest commit of mold, it can be still used if a lto compile is going on, it will fallback to the other linker. 

Here you can find GCC 11.2 precompiled with the patch:

https://cloud.ptr1337.dev/s/Xz2454Lbzpmpxmk


Regards.

**Comment by ghost** [comment]
Thanks for the fixes and the patched gcc! Now I can start experimenting with the new mold linker. Off to do some builds :-)

Regards and take care over there!

**Comment by ptr1337** [comment]
Hey @glitsj16 

I faced into issues with the "new" lto function which is implemented. 
If a PKGBUILD got as options following in:
options=(!lto)

Then the PKGBUILD fails and it says that the option is not there. 

Do you face the problem also? Ive reverted the changes at lto with latest commit. 

Personally i checked it with the PKGBUILD from ungoogled-chromium

Regards

**Comment by ptr1337** [comment]
And one more thing. 

If I try to compile for example GCC with mold enabled and with the LDFLAGS,CXFLAGS enabled with mold '(the changes with the commit which you found the "issue", ill face into errors at compiling.
Nothing compiles. I think we should revert this.

**Comment by ghost** [comment]
Sorry for the late reply. I had some problems after installing the patched gcc 11.2, it hosed my system :-) For now I've put off building with mold until I can spend some time focussing on the things involved. Please feel free to go ahead with reverting anything you deem necessary. I'll definately return to this topic in a few days and will report back.

**Comment by ptr1337** [comment]
Which problems did you faced when installed the gcc version ?

**Comment by ptr1337** [comment]
https://github.com/ptr1337/makepkg-optimize/commit/2705fc96a738ac1cb5d23b4d7de7b31b91ee82ec

Now its fixed :) 

Currently running a build and its correctly used.

**Comment by ghost** [comment]
> Which problems did you faced when installed the gcc version ?

Right after installing gcc and gcc-libs I started to get `Illegal Instruction` left and right and several of my home-grown scripts and locally built packages started to fail. It isn't related to mold or your optimized makepkg stuff, as I couldn't get that far due to the apparent mismatch now being thrown. I reverted to the repo's gcc/gcc-libs using my backup OS on the same box. As long-time collaborator to the [firejail](https://github.com/netblue30/firejail) project I needed to work on a few things ASAP and didn't want to deep dive into mold right now. In that capacity I regularly install/rebuild packages to create/test/debug firejail profiles and mold could be a time-saver or so I thought. For the moment I simply need a working box I can count on to do the work, nothing else :-)

**Comment by ptr1337** [comment]
Oh okay. Then just compile it yourself, my system libs are most self compiled :)

**Comment by ghost** [comment]
Indeed, I've got your patch so I'm ready to go. Thanks for that!

**Comment by ptr1337** [comment]
Here is a PKGBUILD based on this from arch, but using the latest stable gcc commit. So it uses 11.2.1 as gcc version. also there are several gentoo patches included. Also isl 0.24 is with in the package, since arch is not able to fix the link but can still build the packages.. really weird :D 

There you go:

https://cloud.ptr1337.dev/s/cfc3LTXRqS39Dbe
